### ISSUE TITLE
PHP 7 Support.

### ISSUE THREAD

**Issue by chadicus** [dominionenterprises/util-php#55]
Since the current version on supports up to php 5.6. The EOL for 5.5 is a month away and 5.6 only has  a few months of active support.  Should we make v2 of this library support version 7.0 only?

**Comment by nubs** [comment]
I could definitely see that.  You can see similar things happening with major projects like PHPUnit being pretty aggressive at moving forward by holding support for non-current PHP versions back to older versions of the project and encouraging upgrading quickly.

**Comment by chrisryan** [comment]
In order to allow for us to make a transition we will need to have the new code that supports Php 7 running in an environment that is Php 5.6. As such I think we need to at least support 5.6 for making the transition.
